import "bootstrap/dist/css/bootstrap.css";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Seyed Hossein Hosseini Blog",
  description: "This blog generated by create next app",
};

export default async function RootLayout({ children }) {
  const res = await fetch("http://localhost:8085/api/posts/");
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
